[package]
name = "s39"
version = "0.1.0"
authors = ["dcow <david@uno.app>"]
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
anyhow = "1.0"
failure = "0.1"
rand = "0.8"

[dependencies.sssmc39]
version = "0.0.3"
features = ["rust_crypto_pbkdf2"]
default-features = false

