[package]
name = "s39"
version = "0.1.0"
authors = ["dcow <david@withuno.com>"]
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
anyhow = "1.0"
failure = "0.1"
rand = "0.8"
sssmc39 = "0.0.3"
