blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
#control_brace_style = "ClosingNextLine"
fn_single_line = true
format_strings = true
license_template_path = ".rustfmt.license-template"
match_block_trailing_comma = true
max_width = 80
trailing_comma = "Always"
unstable_features = true
use_small_heuristics = "Off"
version = "Two"
wrap_comments = true

