name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: rustup toolchain install nightly
    - name: Install rustfmt
      run: rustup +nightly component add rustfmt
    - name: Check
      run: cargo +nightly fmt --check --verbose
    - name: Build
      run: cargo +nightly build --verbose
    - name: Tests
      run: cargo +nightly test --verbose
